# 366140438193.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day5
name: bootcamp Build-Push

on:
  push:
    branches:
      - main
    paths:
      - 'day4/**' 
      - '.github/workflows/bootcamp-ecs-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 366140438193.dkr.ecr.ap-south-1.amazonaws.com
    - name: Build, Tag, and Push Docker Image
      run: |
        cd day4/src
        docker build -t 366140438193.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day5 .
        docker push 366140438193.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day5
